version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "09:30"
    timezone: Australia/Perth
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.1
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: react-content-loader
    versions:
    - 6.0.1
    - 6.0.2
- package-ecosystem: npm
  directory: "/serverless"
  schedule:
    interval: weekly
    day: saturday
    time: "09:30"
    timezone: Australia/Perth
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: sharp
    versions:
    - 0.28.0
  - dependency-name: "@types/sharp"
    versions:
    - 0.27.1
    - 0.27.2
    - 0.27.3
  - dependency-name: aws-sdk
    versions:
    - 2.853.0
    - 2.868.0
