# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Let's get setup with Node
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - run: sudo apt-get install libnss3-tools
    - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    # Add Homebrew to path
    # c.f. https://github.community/t5/GitHub-Actions/Installing-Homebrew-on-Linux/td-p/51916
    - run: echo "::add-path::/home/linuxbrew/.linuxbrew/bin"
#     - run: sudo apt-get install build-essential
#     - run: echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> /home/runner/.bash_profile
#     - run: brew help
    - run: brew --version
      
    - run: brew install mkcert
    - run: mkcert --version
    
    - name: Setup local dev certs
      run: |
        mkcert -install
        mkdir dev-certs
        cd dev-certs
        mkcert localhost
        mv localhost-key.pem key.pem
        mv localhost.pem cert.pem
    
    # Install frontend and backend (so we can lint)
    - run: yarn install
    - run: cd serverless && yarn install && cd ../
    
    # Are we lint-happy?
    - run: yarn lint
    
    # Are we lint-happy?
    - run: yarn start
      
    # WIP Attempt at starting locally and taking a screenshot of the UI
    # Needs HTTPS certs configured
#     - run: yarn start
#     - name: Take photo of our local build
#       uses: "lannonbr/puppeteer-screenshot-action@1.0.0"
#       with:
#         url: https://localhost:3000
